### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by J-Massey** [Romit-Maulik/PyParSVD#3]
Hi, is there any way I can cite this repo, I've been using it and it's great. I'd like to give you credit.

jonah

**Comment by Romit-Maulik** [comment]
Hi Jonah. Many thanks for the kind words. You can use our Arxiv submission (https://arxiv.org/pdf/2108.08845.pdf) as a citation. 

P.S. We would be extremely grateful if you could contribute to our tutorials and in general spread the word :)

**Comment by J-Massey** [comment]
Thank you!
